#服务配置
server:
  port: 8080
#日志配置
logging:
  config: classpath:logback.xml
  level:
    com:
     company:
       project:
        mapper: debug
#context-listener监听
context:
  listener:
    classes: com.stars.project.listener.ApplicationEventListener
flyway.baselineOnMigrate: true
#数据库配置
spring:
  profiles:
    active: dev
  application:
    name: manager
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
  jpa:
    open-in-view: true
    show-sql: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

#查看运行情况。是否敏感
management:
  security:
    enabled: false
---
#生产环境
spring:
  profiles: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
     filters: stat,wall,log4j
     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
     min-idle: 5
     max-active: 20
     initial-size: 5
     max-wait: 60000
     time-between-eviction-runs-millis: 60000
     min-evictable-idle-time-millis: 300000
     url: jdbc:mysql://192.168.1.6:3306/elderly_community_manager?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
     username: root
     password: root
---
#开发环境
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      min-idle: 5
      max-active: 20
      initial-size: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      url: jdbc:mysql://192.168.1.6:3306/elderly_community_manager?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: stars2018