#服务配置
server:
  port: 8080
#  context-path: /movie
#日志配置
logging:
  config: classpath:logback.xml
  level:
    com:
     company:
       project:
        mapper: debug
#context-listener监听
context:
  listener:
    classes: com.stars.project.listener.ApplicationEventListener
#数据库配置
spring:
  profiles:
    active: dev
  application:
    name: movie
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
  jpa:
    open-in-view: true
    show-sql: true
#redis配置 使用spring starter 待完善
#  redis:
#    host: 192.168.1.188
#    port: 6379
#    pool:
#      max-idle: 4
#      min-idle: 1
#      max-wait: 4000
#      max-active: 4
#mybatis配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
  type-aliases-package: com.company.project.model
#查看运行情况。是否敏感
management:
  security:
    enabled: false

---
#生产环境
spring:
  profiles: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
     filters: stat,wall,log4j
     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
     min-idle: 5
     max-active: 20
     initial-size: 5
     max-wait: 60000
     time-between-eviction-runs-millis: 60000
     min-evictable-idle-time-millis: 300000
     url: jdbc:mysql://127.0.0.1:3306/movie?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
     username: root
     password: root
---
#开发环境
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      min-idle: 5
      max-active: 20
      initial-size: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      url: jdbc:mysql://127.0.0.1:3306/movie?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root